---
dataset_type: 'image'
location_data:
    input_path: '/home/malav312/Desktop/Academics@ASU/CSE598_ODL/Graph_VQA_Implementation/0' #input path to main directory containing driving sequence subdirectories to be processed
    data_save_path: '/home/malav312/Desktop/Academics@ASU/CSE598_ODL/Graph_VQA_Implementation/checkpt.pkl' #path to where processed data should be saved
frame_data:
    frames_limit: 5 #process 1 frame every n frames per sequence subdirectory. Options:  null(None), Integer n
output_format: #specify the shape of each processed frame array
    height: 72 
    width: 128
    color: "RGB" #Color channels. Options: 'RGB', 'Grayscale'
